[package]
name = "mdns"
version = "0.2.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]

description = "A multicast DNS client"
license = "MIT"
documentation = "https://docs.rs/mdns"
repository = "https://github.com/dylanmckay/mdns"

keywords = ["mdns", "dns", "multicast", "chromecast"]

[dependencies]
mio = "0.6"
dns-parser = "0.7"
net2 = "0.2"
error-chain = "0.10"
ifaces = "0.1.0"
